# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2afe400c1e7b846f791ba79f58269df4b4128a3480b6f362a4be9a78213eec031e991c55a70b2e44db1d928a2b7f1d82497371cb9996845e095d042e4e1ca260

test:
  secret_key_base: f79ecf07fe126c04a0d71488cb2b95aa1dde398af30437de91e7fc4f0ee003dabdebae4fc6d3bf9ee115f17618cf89ede7e8f76f74b610f240810b652f8b8271

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
